output_dir: "results"
log_dir: "logs"
benchmark_dir: "benchmarks"
threads: 12
mem: 20
samples:
  "200080":
    asm_dir: "data/asm/200080"
    asm_rgx: ".*\\.(fasta|fasta.gz)$"
    read_dir: "data/element/200080"
    read_rgx: ".*\\.gz$"
